# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mclub.ui'
#
# Created: Sun Mar 02 20:55:39 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mclub.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtGui.QTreeView(self.groupBox)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeView.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.treeView.setAutoExpandDelay(0)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.destButton = QtGui.QPushButton(self.groupBox_4)
        self.destButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.destButton.setObjectName("destButton")
        self.gridLayout_3.addWidget(self.destButton, 0, 1, 1, 1)
        self.lblDestPath = QtGui.QLabel(self.groupBox_4)
        self.lblDestPath.setEnabled(False)
        self.lblDestPath.setObjectName("lblDestPath")
        self.gridLayout_3.addWidget(self.lblDestPath, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ckbxTrimDir = QtGui.QCheckBox(self.groupBox_5)
        self.ckbxTrimDir.setObjectName("ckbxTrimDir")
        self.gridLayout.addWidget(self.ckbxTrimDir, 0, 0, 1, 2)
        self.lblTrimDir = QtGui.QLabel(self.groupBox_5)
        self.lblTrimDir.setObjectName("lblTrimDir")
        self.gridLayout.addWidget(self.lblTrimDir, 1, 0, 1, 1)
        self.trimdirCount = QtGui.QSpinBox(self.groupBox_5)
        self.trimdirCount.setSingleStep(1)
        self.trimdirCount.setObjectName("trimdirCount")
        self.gridLayout.addWidget(self.trimdirCount, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbOWDest = QtGui.QCheckBox(self.groupBox_5)
        self.cbOWDest.setObjectName("cbOWDest")
        self.gridLayout_2.addWidget(self.cbOWDest, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbOWNewer = QtGui.QRadioButton(self.groupBox_5)
        self.rbOWNewer.setObjectName("rbOWNewer")
        self.verticalLayout.addWidget(self.rbOWNewer)
        self.rbOWLarger = QtGui.QRadioButton(self.groupBox_5)
        self.rbOWLarger.setObjectName("rbOWLarger")
        self.verticalLayout.addWidget(self.rbOWLarger)
        self.rbOWEither = QtGui.QRadioButton(self.groupBox_5)
        self.rbOWEither.setObjectName("rbOWEither")
        self.verticalLayout.addWidget(self.rbOWEither)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.copyButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyButton.sizePolicy().hasHeightForWidth())
        self.copyButton.setSizePolicy(sizePolicy)
        self.copyButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayout_5.addWidget(self.copyButton)
        self.closeButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_5.addWidget(self.closeButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtGui.QListWidget(self.groupBox_2)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.previewView = QtGui.QListWidget(self.groupBox_6)
        self.previewView.setObjectName("previewView")
        self.horizontalLayout_3.addWidget(self.previewView)
        self.gridLayout_4.addWidget(self.groupBox_6, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionChoose_Destination = QtGui.QAction(MainWindow)
        self.actionChoose_Destination.setObjectName("actionChoose_Destination")
        self.actionChoose_Source = QtGui.QAction(MainWindow)
        self.actionChoose_Source.setObjectName("actionChoose_Source")
        self.actionStart_Copy = QtGui.QAction(MainWindow)
        self.actionStart_Copy.setObjectName("actionStart_Copy")
        self.menuFile.addAction(self.actionChoose_Destination)
        self.menuFile.addAction(self.actionChoose_Source)
        self.menuFile.addAction(self.actionStart_Copy)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered(bool)"), MainWindow.close)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.ckbxTrimDir, QtCore.SIGNAL("toggled(bool)"), self.trimdirCount.setVisible)
        QtCore.QObject.connect(self.ckbxTrimDir, QtCore.SIGNAL("toggled(bool)"), self.lblTrimDir.setVisible)
        QtCore.QObject.connect(self.cbOWDest, QtCore.SIGNAL("toggled(bool)"), self.rbOWEither.setVisible)
        QtCore.QObject.connect(self.cbOWDest, QtCore.SIGNAL("toggled(bool)"), self.rbOWLarger.setVisible)
        QtCore.QObject.connect(self.cbOWDest, QtCore.SIGNAL("toggled(bool)"), self.rbOWNewer.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MC Mover", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Source View", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.destButton.setText(QtGui.QApplication.translate("MainWindow", "Pick Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDestPath.setText(QtGui.QApplication.translate("MainWindow", "Please select Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbxTrimDir.setText(QtGui.QApplication.translate("MainWindow", "Trim Directory Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTrimDir.setText(QtGui.QApplication.translate("MainWindow", "Number of Dirs", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOWDest.setText(QtGui.QApplication.translate("MainWindow", "Overwrite Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOWNewer.setText(QtGui.QApplication.translate("MainWindow", "If Newer", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOWLarger.setText(QtGui.QApplication.translate("MainWindow", "If Larger", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOWEither.setText(QtGui.QApplication.translate("MainWindow", "If Newer or Larger", None, QtGui.QApplication.UnicodeUTF8))
        self.copyButton.setText(QtGui.QApplication.translate("MainWindow", "Start Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Selected Items", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChoose_Destination.setText(QtGui.QApplication.translate("MainWindow", "Choose Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChoose_Source.setText(QtGui.QApplication.translate("MainWindow", "Choose Source", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Copy.setText(QtGui.QApplication.translate("MainWindow", "Start Copy", None, QtGui.QApplication.UnicodeUTF8))

